import { Button, StyleSheet } from 'react-native';

export default StyleSheet.create({
scrollContainer: {
    flexGrow: 1,
    backgroundColor: '#f0f0f0',
    
  },
  container: {
    padding: 10,
    width: '95%',
    backgroundColor: '#fff',
    borderRadius: 10,
    paddingVertical: 30,
    paddingHorizontal: 20,
    margin: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    alignItems: 'center'
  },

  headerTopBar: {
    backgroundColor: '#4369F1',
    paddingHorizontal: 12,
    elevation: 2,
    marginBottom: 12,
    alignItems: 'center',
    width: '95%',
    xIndex:99,
    marginTop:10,
    borderRadius: 10,
    overflow: 'hidden',
    marginLeft:8,
    top: 5
  },
  headerTopBarText: {
    marginTop:20,
    color: '#fff',
    fontSize: 20,
    fontWeight: 'bold',
  },
  headerLeftBarText: {
   color: '#fff',
  flex: 1,
  fontSize: 14,
  marginRight:10,
  },
  video:{
    width:100,
    height:100,
    resizeMode:'cover',
   },

  row:{
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
    flexWrap: 'wrap', // Adiciona quebra automática de linha
  },
  inputContainer:{
   flexDirection: 'row',
   width: '100%',
   alignItems: 'center',
   borderColor: '#4369F1',
   borderWidth:1,
   borderRadius:30,
   padding: 5,
   marginBottom: 10,
   borderWidth:2,
   shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  iconContainer:{
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    width:30,
    height:30,
    borderRadius:30,
    backgroundColor: '#4369F1',
  },
  EntradaText: {
   flex: 1,
   height: 45,
   fontSize: 16,
  },
 
  container2: {
    flex: 1,
    justifyContent: 'center',
    alignItems:'center'
 },
 logo: {
  width: 150,
    height: 100,
    alignSelf: 'center',
},
  TextImg: {
  color: 'blue',
  textAlign: 'center',
  marginVertical: 10,
},
label: {
  fontSize: 17,
  fontWeight: 'bold',
  color: '#4369F1', // Cor futurista
  marginTop: 10,
},
imageContainer: {
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'space-between',
  width: '100%',
  marginVertical: 10,
},

//Botões de IMG e expansão
imageButton: {
  width: 100,
  height: 100,
  backgroundColor: '#4369F1',
  justifyContent: 'center',
  alignItems: 'center',
  borderRadius: 10, 
  shadowColor: '#4369F1',
  shadowOffset: { width: 0, height: 4 },
  shadowOpacity: 0.5,
  shadowRadius: 10,
  elevation: 8,
  borderWidth: 1,
  borderColor: '#4369F1', 
},
uploadIcon: {
  width: 35,
  height: 35,
  color: '#fff', 
},
Imagem: {
  width: '50%',
  height: 100,
  justifyContent: 'center',
  alignItems: 'center',
  borderRadius: 10,
  marginTop: 10,
  shadowColor: '#4369F1',
  shadowOffset: { width: 0, height: 4 },
  shadowOpacity: 0.5,
  shadowRadius: 10,
  elevation: 8,
},

submitButton: {
  backgroundColor: '#4369F1', 
  padding: 15,
  borderRadius: 10,
  shadowColor: '#4369F1',
  shadowOffset: { width: 0, height: 4 },
  shadowOpacity: 0.5,
  shadowRadius: 10,
  elevation: 8,
  marginTop: 20,
},
submitButtonText: {
  color: '#fff',
  textAlign: 'center',
  fontWeight: 'bold',
  fontSize: 18,
},

button: {
    width: '100%',
    padding: 15,
    backgroundColor: '#4369F1',
    borderRadius: 30,
    alignItems: 'center',
    marginTop: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
  },
  Containerbotao:{
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10, 
    padding: 15,
    bottom: 10,
marginTop: 10,
  },
  ExpancaoButton:{
   width: 60,
    height: 60,
    backgroundColor: '#007bff',
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 20,
    shadowColor: '#4369F1',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
    elevation: 10,
    padding: 15,
  },
  ExpancaoButtonText:{
   width: '70%', 
    backgroundColor: '#007bff',
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 20,
    shadowColor: '#4369F1',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
    elevation: 10,
    padding: 15,
  },
  plusIcon: {
  width: 32,
  height: 32,
  color: '#fff', 
},
  BotaoExpancao:{
    color: '#fff',
    fontSize: 16,
  },
  expandedContainer: {
    marginTop:0, 
  alignItems:'center',
justifyContent: 'center' },
    
  colunmButton:{
  flexDirection:'row',
  width: '100%',
  alignItems: 'center',
    },

  actionButton: {
    width: 80,
    height: 80,
    backgroundColor: '#D6C420',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10, 
    shadowColor: '#D6C420',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
    elevation: 8,
    borderWidth: 1,
    borderColor: '#D6C420', 
    marginRight:20,
  },
  actionButton2: {
    width: 80,
    height: 80,
    backgroundColor: '#28a745',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10, 
    shadowColor: '#28a745',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
    elevation: 8,
    borderWidth: 1,
    borderColor: '#28a745', 
    marginRight:20,
  },
  actionButton3: {
    width: 80,
    height: 80,
    backgroundColor: '#DE1A1A',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10, 
    shadowColor: '#DE1A1A',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
    elevation: 8,
    borderWidth: 1,
    borderColor: '#DE1A1A',
    
  },
  buttonText: {
    color: '#fff',
    fontSize: 12,
  },
  

  //Perfil imagem
  PerfilImage: {
    width:'100%',
    height: '100%', 
    borderRadius: 15,
    borderWidth: 5,
    borderColor: '#fff',
    borderWidth: 3,
    borderColor: '#4369F1',
   
  },

  //
});